### PR TITLE
Test of ChatRoomService

### PR DESCRIPTION
**Pull request by madsboddum**
1. Players enter chat rooms when they zone in the first time
2. Players do not enter the same chat room when they teleport
3. Admin players enter the server log channel

### CODE REVIEW

**Comment by madsboddum** [comment]
Failure:
```
com.projectswg.holocore.services.support.global.chat.TestChatRoomService > testNotifyWhenMemberEnters FAILED
    java.lang.RuntimeException at TestChatRoomService.java:32
        Caused by: java.io.FileNotFoundException at TestChatRoomService.java:32
```
Works alright locally in IntelliJ, obviously can't find some file. Gradle wrapper completely broke for me recently so I can't test that locally.

**Comment by Josh-Larson** [comment]
Code looks fine, will wait for that test to pass

**Comment by madsboddum** [comment]
@Josh-Larson I'm *guessing* file creation isn't allowed when running the tests on GitHub, because it runs fine locally - even using the gradle wrapper. `ChatRoomService` tries to create an ODB file at some point.

A potential solution could be dependency injection of the `ObjectDatabase<ChatRoom>` and then having some simple in-memory storage. What do you think of that?

Codepointer to ODB: `ChatRoomHandler:61`

**Comment by madsboddum** [comment]
Ah, I just noticed that `ObjectDatabase` isn't an interface - it's an abstract class that has all the file handling inside. That's a bit unfortunate.

**Pull request closed without merging**
