### PR TITLE
Cone of Effect attacks #77

### LINKED ISSUE #77: COE (Cone Of Effect)
These are attacks that can hit all targets in a cone area in front of the user. COE-based weapons can stack DoTs at a faster rate than their AOE-based counterparts.

### PR DESCRIPTION
**Pull request by madsboddum**
Fixes #77

### CODE REVIEW

**Comment by Undercova** [comment]
- equip Republic Flamethrower from CBT
- switch to free aiming
- shoot somewhere on ground

image

**Comment by madsboddum** [comment]
Hadn't considered heavy weapons with this.

**Comment by Undercova** [comment]
Attacks that have CoE /// combat_data.iff /// attackType has to be "CONE" !!

Jedi - Shockwave /// fs_dm_cc_crit_5 /// 32 length + 20 width + 32 max range
Jedi - Maelstrom /// fs_maelstrom_5 /// 32 length + 20 width + 32 max range
Commando - Sweeping Fire /// co_ae_dm_3 /// 25 length + 35 width + 0 max range
Bounty Hunter - Burn /// bh_ae_dm_2 /// 35 length + 30 width + 35 max range
Smuggler - Fan Shot /// sm_ae_dm_6 /// 46 length + 25 width + 46 max range

**Comment by madsboddum** [comment]
Also seems like attacks are done in 360 degrees, like AoE. Maybe the math stolen from Core2 is off, or I managed to mess it up somewhere.

**Comment by madsboddum** [comment]
* Disabled unintended handling of flamethrowers in free-target mode
* Cone of Effect attacks no longer attack in 360 degrees

**Pull request merged**
