### PR TITLE
/kill admin command

### LINKED ISSUE #1428: [Admin] /kill command
So we can more easily test things in-game by cheating past combat.

Simply have the command request the death of whatever creature is being targeted.

### PR DESCRIPTION
**Pull request by madsboddum**
Fixes #1428

### CODE REVIEW

**Comment by Undercova** [comment]
Works great :)
BUT ... no loot generated
Intended ?

**Comment by Undercova** [comment]
Well ...
i just performed the command on an INVULNERABLE NPC ... and got massive XP although i already am CL80 Jedi.
This command should not work on them !

image

image

**Comment by madsboddum** [comment]
Agreed, it's just too undefined what will happen in this case.

If that npc never response, you can break the game and only fix it with a server restart.
________________________________

**Comment by Undercova** [comment]
ALL our NPC spawners have a respawn timer. standard is like 10 mins :)
so they all come back

**Comment by madsboddum** [comment]
I suppose that makes the problem go away.

We can still change the behavior of the command to disallow invulnerable NPCs, but I don't feel very strongly about it now.

The fact that we're getting large amounts of (broken) XP from the kills is a problem, though.
________________________________

**Comment by Undercova** [comment]
correct
how about you get no XP at all when NPC is invulnerable ?
so Experience Service has to be adjusted

**Comment by madsboddum** [comment]
I think that makes a lot of sense. No XP from invulnerable NPCs.
________________________________

**Pull request merged**
